//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htcustomer.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProduct
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<int> Amount { get; set; }
        public string Seller { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<double> BuyPrice { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<System.DateTime> BuyDate { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<bool> Disable { get; set; }
    
        public virtual TblProductType TblProductType { get; set; }
    }
}
