//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace htcustomer.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblToDo
    {
        public int ToDoID { get; set; }
        public string Content { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> RemindTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
